name: fiberchat #changing it will force you to change appname in import statement inside every .dart file.
description: Chats & Calling app

version: 1.0.50+51

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_mobile_ads:
  font_awesome_flutter:
  sms_autofill:
  receive_sharing_intent:
  firebase_crashlytics:
  async:
  emoji_picker_flutter:
  flutter_video_info:
  group_button:
  flutter_colorpicker:
  story_view:
  devicelocale:
  cloud_functions:
  http_auth:
  cloud_firestore:
  flutter_cached_pdfview:
  fluttertoast:
  firebase_messaging:
  dio:
  cached_network_image:
  firebase_storage:
  device_info:
  file_picker:
  flutter_image_compress:
  path_provider:
  path:
  flutter_sound:
  percent_indicator:
  string_validator:
  ntp:
  random_string:
  flutter_native_timezone:
  intl:
  connectivity:
  data_connection_checker_tv:
  http:
  provider:
  firebase_auth:
  html:
  image_picker:
  universal_platform:
  flutter_linkify:
  dotted_border:
  url_launcher:
  diacritic:
  image_cropper:
  contacts_service:
  share:
  scoped_model:
  local_auth:
  crypto:
  encrypt:
  localstorage:
  photo_view:
  mime:
  launch_review:
  overlay_support:
  jiffy:
  geolocator:
  video_player:
  video_thumbnail:
  chewie:
  media_info:
  firebase_core:
  shared_preferences:
  permission_handler:
  agora_rtc_engine:
  translator:
  audioplayers:
  flutter_local_notifications:
  flutter_secure_storage:
  package_info:
  flutter_link_previewer:
  fancy_bottom_navigation:
  pinput:
  animations:
  giphy_get:
  wakelock:

  google_maps_flutter: ^2.1.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  collection:
dependency_overrides:
  provider:  # for chewie 1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  flutter_driver:
    sdk: flutter
  test:

#  flutter_launcher_icons: ^0.9.2
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mapview.jpg
    - assets/images/background.png
    - assets/images/applogo.png
    - assets/images/applogo_white.jpeg
    - assets/images/splash.jpeg
    - assets/images/img_not_available.jpeg
    - assets/sounds/popsound.mp3
    - assets/sounds/callingtone.mpeg
    - assets/sounds/ringtone.mp3
    - assets/sounds/whistle.mp3
    - assets/flags/
    - assets/images/
    - lib/Services/localization/json_languages/
